# Generated by Django 4.1.1 on 2022-09-30 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 9, 30, 7, 28, 59, 9942, tzinfo=datetime.timezone.utc), max_length=150),
            preserve_default=False,
        ),
    ]
