# Generated by Django 4.1.1 on 2022-09-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('accounts', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_spam',
        ),
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='user_by_contact', to='contacts.contact'),
        ),
    ]
