# Generated by Django 4.1.1 on 2022-09-30 08:09

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Contact Id')),
                ('label', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[contacts.models.checkPhoneNum])),
                ('is_spam', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'managed': True,
            },
        ),
    ]
